FROM fedora

RUN dnf -y install 'dnf-command(builddep)' nano git make ccache gawk
RUN dnf -y install python3.9 libpq-devel gcc
RUN git clone https://github.com/python/buildmaster-config
ADD makefile.patch ./
WORKDIR buildmaster-config
RUN git apply ../makefile.patch
RUN git config user.name 'Containerized user'
RUN git config user.email 'container@invalid'
RUN make git-update-requirements
RUN make venv
RUN dnf -y install /usr/bin/pgrep
ENV PYBUILDBOT_SETTINGS_PATH=/settings.yaml
ADD settings.yaml ../
RUN make start-master && make update-master && make stop-master
EXPOSE 9011
ENV BUILDBOT_WEB_URL=localhost:40511



# WASI stuff

ARG TARGETARCH


ENV CC=clang

RUN dnf -y --nodocs --setopt=install_weak_deps=False --disablerepo=fedora-cisco-openh264 install \
        /usr/bin/{blurb,clang,curl,git,ln,tar,xz} \
        compiler-rt \
        # TODO: remove when Fedora version includes Python 3.14+
        libzstd-devel \
        'dnf5-command(builddep)' && \
    dnf -y --nodocs --setopt=install_weak_deps=False --disablerepo=fedora-cisco-openh264 \
        builddep python3 && \
    dnf -y clean all


# Update only after consulting with WASI support maintainers (see PEP 11).
ENV WASI_SDK_VERSION=24
ENV WASI_SDK_PATH=/opt/wasi-sdk

RUN mkdir ${WASI_SDK_PATH} && \
    case "${TARGETARCH}" in \
        amd64) WASI_ARCH="x86_64" ;; \
        arm64) WASI_ARCH="arm64" ;; \
        *) echo "Unsupported TARGETARCH: ${TARGETARCH}" && exit 1 ;; \
    esac && \
    curl --location https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-${WASI_SDK_VERSION}/wasi-sdk-${WASI_SDK_VERSION}.0-${WASI_ARCH}-linux.tar.gz | \
    tar --strip-components 1 --directory ${WASI_SDK_PATH} --extract --gunzip


# Update as desired.
ENV WASMTIME_VERSION=33.0.0
ENV WASMTIME_HOME=/opt/wasmtime

RUN mkdir --parents ${WASMTIME_HOME} && \
    case "${TARGETARCH}" in \
        amd64) WASMTIME_ARCH="x86_64" ;; \
        arm64) WASMTIME_ARCH="aarch64" ;; \
        *) echo "Unsupported TARGETARCH: ${TARGETARCH}" && exit 1 ;; \
    esac && \
    curl --location "https://github.com/bytecodealliance/wasmtime/releases/download/v${WASMTIME_VERSION}/wasmtime-v${WASMTIME_VERSION}-${WASMTIME_ARCH}-linux.tar.xz" | \
    xz --decompress | \
    tar --strip-components 1 --directory ${WASMTIME_HOME} -x && \
    ln -s ${WASMTIME_HOME}/wasmtime /usr/local/bin

CMD make start-master; bash
